<template>
	<section class="definition">
		<h4>Definitions</h4>
		<p class="list_heading">For the purposes of this Privacy Policy:</p>
		<ul>
			<li><strong>Account</strong> means a unique account created for You to access our Service or parts of our Service.</li>
			<li>
				<strong>Company</strong> (referred to as either "the Company", "We", "Us" or "Our" in this Agreement) refers to Volley,
				Toronto, ON CA.
			</li>
			<li>
				<strong>Cookies</strong> are small files that are placed on Your computer, mobile device or any other device by a website,
				containing the details of Your browsing history on that website among its many uses.
			</li>
			<li><strong>Country</strong> refers to: Ontario, Canada</li>
			<li>
				<strong>Device</strong> means any device that can access the Service such as a computer, a cellphone or a digital tablet.
			</li>
			<li><strong>Personal</strong> Data is any information that relates to an identified or identifiable individual.</li>
			<li><strong>Service</strong> refers to the Website.</li>
			<li>
				<strong>Service</strong> Provider means any natural or legal person who processes the data on behalf of the Company. It
				refers to third-party companies or individuals employed by the Company to facilitate the Service, to provide the Service on
				behalf of the Company, to perform services related to the Service or to assist the Company in analyzing how the Service is
				used.
			</li>
			<li>
				<strong>Usage Data</strong> refers to data collected automatically, either generated by the use of the Service or from the
				Service infrastructure itself (for example, the duration of a page visit).
			</li>
			<li>
				<strong>Website</strong> refers to Volley, accessible from
				<a href="https://www.volley.com/">https://www.volley.com/</a>
			</li>
			<li>
				<strong>You</strong> means the individual accessing or using the Service, or the company, or other legal entity on behalf of
				which such individual is accessing or using the Service, as applicable.
			</li>
		</ul>
	</section>
</template>
<script>
export default {
	name: 'Definition'
};
</script>

<style></style>
