# This is a basic workflow to help you get started with Actions

name: Node.js CI

on:
  pull_request:
    branches: [ develop ]

jobs:
  coverage:
    name: coverage
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-node@master
      with:
        node-version: '10'
    - run: npm install
    - uses: paambaati/codeclimate-action@v2.7.4
      env:
        CC_TEST_REPORTER_ID: '6308d30d4029f32a6e6565d464452fdeba7d185b883515f00d0706ee42430b01'
      with:
        coverageCommand: npm run test -- --coverage
